export const CATELOGO_SCHEMA_V1 = {
    tipoProcesoEmpacado: '++_pk,id,idproyecto,&codigo,nombre,activo,fechaCreacion,bd',
    configuracion:'++_pk,&nrodocumento,idFundo,codigoCultivo,idProyecto',
    fundo: '++_pk,id,&codigoFundo,empresa,fundo,nombreFundo',
    cultivos: '++_pk,id,empresa,cultivo,&codigo,descripcion,estado,bd',
    campanias: '++_pk,&idproyecto,descripcion,fecha_inicio,fecha_fin,ruc,estado,codcultivo,codigoSpring,aplicacion,idfundo,fruta',
    clientes : '++_pk,id,&codigo,nombre,activo,fechaCreacion,bd',
    consignatarios : '++_pk,id,&documento,nombre,codigoGrupoCliente,nombreGrupoCliente,bd',
    destinos : '++_pk,&id,pais,nacionalidad',
    formatos: '++_pk,&id,codigoCultivo,codigo,descripcion,pesoPorCaja,limiteCajasPorPalet,activo,fechaCreacion,bd',
    calibres: '++_pk,&id,calibre,idCultivo',
    categorias: '++_pk,&id,calibreId,calibreNombre,codigoCultivo,codigo,nombre,descripcion,activo,fechaCreacion,bd',
    tiposEmpaque: '++_pk,&id,codigoCultivo,codigo,descripcion,activo,fechaCreacion,bd',
    tiposEmpaqueGuia: '++_pk,&id,codigoCultivo,codigo,nombre,activo,fechaCreacion,bd',
    presentaciones: '++_pk,id,&codigo,nombre,activo,fechaCreacion,bd',
    tiposCaja: '++_pk,&id,codigoCultivo,codigo,nombre,activo,fechaCreacion,bd',
    tiposClamshell: '++_pk,&id,codigoCultivo,codigo,nombre,activo,fechaCreacion,bd',
    variedades: '++_pk,id,idcultivo,&codigo,idvariedad,variedad,procedencia,esEnsayo,eliminado,bd',
    lugaresProduccion: '++_pk,&id,idproyecto,codigo,descripcion,activo,fechaCreacion,bd',
    transportes: '++_pk,&id,transporte,factorTEUtoPallet',
    codigosRancho: '++_pk,&id,codigo,activo,fechaCreacion,bd',
    lugaresProduccionConfig: '++_pk,&id,idproyecto,idCodigoRancho,idLugaresDeProduccion,activo,fechaCreacion,bd',
    destinatarios:'++_pk,id,idCliente,&documentoFiscal,documento,nombre,domicilioFiscal,puntoLlegada,activo,fechaCreacion,bd',
    codigosCaja: '++_pk,id,codigoItem,documentoConsignatario,idDestino,codigoFormato,codigoVariedad,idTipoEmpaqueGuia,codigoRancho,idLugarProduccion,idPresentacion,pesoPorCaja,idTransporte,fechaCreacion,bd'
}