-- =================================================================
-- SCRIPT PARA OBTENER ESTRUCTURA COMPLETA DE LA BASE DE DATOS
-- =================================================================
-- Ejecuta este script en tu SQL Server y comparte los resultados
-- para poder crear los stored procedures correctos

-- 1. LISTAR TODAS LAS TABLAS
SELECT '=== TABLAS ===' as Info;
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;

-- 2. ESTRUCTURA DE TABLAS PRINCIPALES (PALETS RELACIONADAS)
SELECT '=== ESTRUCTURA TABLA PALETS ===' as Info;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Palets' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;

SELECT '=== ESTRUCTURA TABLA PALETCOMPOSICION ===' as Info;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PaletComposicion' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;

-- 3. ESTRUCTURA DE TABLAS RELACIONADAS
SELECT '=== ESTRUCTURA TABLA PROCESOS ===' as Info;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Procesos' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;

SELECT '=== ESTRUCTURA TABLA ACOPIOS ===' as Info;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Acopios' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;

SELECT '=== ESTRUCTURA TABLA FORMATOS ===' as Info;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Formatos' 
    AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;

-- 4. LISTAR TABLAS DE CATÁLOGOS
SELECT '=== TABLAS DE CATÁLOGOS ===' as Info;
SELECT 
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' 
    AND TABLE_SCHEMA = 'dbo'
    AND (
        TABLE_NAME LIKE '%Cliente%' 
        OR TABLE_NAME LIKE '%Consignatario%'
        OR TABLE_NAME LIKE '%Destino%'
        OR TABLE_NAME LIKE '%Variedad%'
        OR TABLE_NAME LIKE '%Calibre%'
        OR TABLE_NAME LIKE '%Empaque%'
        OR TABLE_NAME LIKE '%Caja%'
        OR TABLE_NAME LIKE '%Clamshell%'
        OR TABLE_NAME LIKE '%Presentacion%'
        OR TABLE_NAME LIKE '%Produccion%'
        OR TABLE_NAME LIKE '%Rancho%'
        OR TABLE_NAME LIKE '%Transporte%'
        OR TABLE_NAME LIKE '%Categoria%'
        OR TABLE_NAME LIKE '%Campania%'
    )
ORDER BY TABLE_NAME;

-- 5. STORED PROCEDURES EXISTENTES
SELECT '=== STORED PROCEDURES EXISTENTES ===' as Info;
SELECT 
    name,
    create_date,
    modify_date
FROM sys.procedures 
WHERE name LIKE '%Palet%' 
    OR name LIKE '%palet%'
    OR name LIKE '%Composicion%'
ORDER BY name;

-- 6. REVISAR SI EXISTEN LAS TABLAS PRINCIPALES
SELECT '=== VERIFICACIÓN DE TABLAS PRINCIPALES ===' as Info;
SELECT 
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Palets') 
        THEN 'EXISTS' 
        ELSE 'MISSING' 
    END as Palets,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PaletComposicion') 
        THEN 'EXISTS' 
        ELSE 'MISSING' 
    END as PaletComposicion,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Procesos') 
        THEN 'EXISTS' 
        ELSE 'MISSING' 
    END as Procesos,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Acopios') 
        THEN 'EXISTS' 
        ELSE 'MISSING' 
    END as Acopios,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Formatos') 
        THEN 'EXISTS' 
        ELSE 'MISSING' 
    END as Formatos;
