export const CATELOGO_SCHEMA_V1 = {
    clientes : '++_pk,id,&codigo,razonSocial,activo,bd',
    consignatarios : '++_pk,id,&codigo,razonSocial,activo,bd',
    destinos : '++_pk,id,&codigo,nombre,pais,activo,bd',
    formatos: '++_pk,id,&codigo,descripcion,nombre,pesoPorCaja,limiteCajasPorPalet,activo,bd',
    calibres: '++_pk,id,&codigo,nombre,activo,bd',
    categorias: '++_pk,id,&codigo,nombre,descripcion,activo,fechaCreacion,bd',
    tiposEmpaque: '++_pk,id,&codigo,descripcion,activo,bd',
    tiposEmpaqueGuia: '++_pk,id,&codigo,nombre,activo,fechaCreacion,bd',
    presentaciones: '++_pk,id,&nombre,descripcion,activo,fechaCreacion,bd',
    tiposCaja: '++_pk,id,&codigo,nombre,activo,fechaCreacion,bd',
    tiposClamshell: '++_pk,id,&codigo,nombre,activo,fechaCreacion,bd',
    variedades: '++_pk,id,&codigo,nombre,presedencia,esEnsayo,activo,bd',
    lugaresProduccion: '++_pk,id,&codigo,nombre,descripcion,activo,bd',
    transportes: '++_pk,id,&codigo,nombre,descripcion,activo,fechaCreacion,bd',
}